### ISSUE TITLE
Cannot read the property ref

### ISSUE THREAD

**Issue by SaiKiran322** [nathvarun/React-Native-Firebase-Tutorials#1]
TypeError: Cannot read property 'ref' of undefined
    at exports.sendPushNotification.functions.database.ref.onCreate.snap (/user_code/index.js:80:27)
    at cloudFunctionNewSignature (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:105:23)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:135:20)
    at /var/tmp/worker/worker.js:744:24
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by waqaramjad** [comment]
i am getting the same error any solution for that
