### ISSUE TITLE
not working in Firebase Spark plane 

### ISSUE THREAD

**Issue by waqaramjad** [nathvarun/React-Native-Firebase-Tutorials#4]
Hi i am using Firebase spark plane and it give me error , i check about that they ask me to buy the blaze plane for that , is it possible to that in spark plane 

FetchError: request to https://exp.host/--/api/v2/push/send failed, reason: getaddrinfo ENOTFOUND exp.host exp.host:443
    at ClientRequest.<anonymous> (/user_code/node_modules/node-fetch/lib/index.js:1444:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1040:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by nathvarun** [comment]
Yea I mentioned that in the video. 
The Blaze Plan also has a free tier.
